### ISSUE TITLE
Manual Form for a Stream Configuration

### ISSUE THREAD

**Issue by alonweissfeld** [beyond-io/sellotape#34]
Since we're only retrieving data from platforms (twitch, youtube, etc.) about some users streams, we do not upload any podcast or audio files by ourselves. But, we want to add flexibility. Therefore, create a form that lets the user add streaming information that is not retrieved automatically by us. It should have the relevant fields to insert a link, time, and other fields that are included in the `Stream` Model.

The html form will make a POST request and will add a new `Stream` instance to the database with the relevant information.

**Comment by rosomri** [comment]
was solved #86
