### ISSUE TITLE
Login/Register 

### ISSUE THREAD

**Issue by alonweissfeld** [beyond-io/sellotape#6]
Create a Login/Register system to the site, using Google and Facebook authentication.

Some helpful links:

With [`social-auth`](https://github.com/python-social-auth/social-app-django):
https://www.digitalocean.com/community/tutorials/django-authentication-with-facebook-instagram-and-linkedin
https://realpython.com/adding-social-authentication-to-django/
https://medium.com/trabe/oauth-authentication-in-django-with-social-auth-c67a002479c1

With [`all-auth`](https://django-allauth.readthedocs.io/en/latest/installation.html)
https://medium.com/@whizzoe/in-5-mins-set-up-google-login-to-sign-up-users-on-django-e71d5c38f5d5
https://medium.com/@jinkwon711/django-allauth-facebook-login-b536444cbc6b

**Comment by alonweissfeld** [comment]
@11galpid Can you push the working branch to your repo and link it here? :)

**Comment by 11galpid** [comment]
Sure,
https://github.com/11galpid/sellotape/tree/dev-userlogin
